---
title: "Taller1_Seccion2_Punto2"
output: html_notebook
---
Implemente en R o Python un algoritmo que le permita sumar los n
2 primeros n´umeros naturales al
cuadrado. Imprima varias pruebas, para diferentes valores de n y exprese f(n) en notaci´on O() con una
gr´afica que muestre su orden de convergencia.

////////////////////////////////////////////

Se realizo una función llamada cuadrado que guardaba un variable al cuadrado que permitia en un ciclo crear varias prueba, este ciclo llega hasta un limite que es el valor maximo que se da


```{r}


#creamos los primeros números naturales al cuadrado
n<- y^2
cuadrado <- function(n , val, x_0,err){
  deltax_k  =  1
  es  =  0
  er ? 
  while (abs ( deltax_k ) >  er ) {
    deltax_k  = (( val / ( x_k ** ( n - 1 ))) -  x_k ) / n
    x_k  =  x_k  +  deltax_k
    it  =  it  +  1
  }
}

cat ( " El resultado es " , cuadrado ( n , val , x_0 , err ))


#graficando h(x) vs x
plot.function(f,0,2, pch =19, main = "h(x) en función de x",xlab = " X ",ylab = " h(x) ",col ="black")

#imprime la relación de error -> Convergencia lineal
points(cuadrado, cuadrado, col = "blue")
lines(cuadrado, cuadrado, col = "blue")

```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
